services:

  app:
    image: streamlit-uv-project-ty-ruff-bitbucket-streamlit:latest
    build:
      context: ..
      dockerfile: streamlit/Dockerfile
    restart: unless-stopped
    ports:
      - "8503:8501"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    logging:
      options:
        max-file: "2"
        max-size: "20m"
    depends_on:
      postgres:
        condition: service_healthy

  migrations:
    # Not used build section as already built for main app
    image: streamlit-uv-project-ty-ruff-bitbucket-streamlit:latest
    build:
      context: ..
      dockerfile: streamlit/Dockerfile
    command:
      - alembic
      - upgrade
      - head
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    logging:
      options:
        max-file: "2"
        max-size: "20m"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.7
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - postgres-db-volume-uv-project-ty-ruff-bitbucket-streamlit:/bitnami/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}", "-d", "${POSTGRESQL_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    logging:
      options:
        max-file: "2"
        max-size: "20m"

volumes:
  postgres-db-volume-uv-project-ty-ruff-bitbucket-streamlit:
